const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  feedbacks: [
    {
      id: 'quote-1',
      clientName: 'John Smith',
      clientText:
        'Vestibulum eu ante non enim malesuada vestibulum quis ac nisl. Nullam eget lacus iaculis, blandit augue in, pulvinar ipsum. Curabitur quis ligula tempus, tristique sapien pulvinar, dictum enim. Etiam tempor mollis tellus, id interdum ipsum condimentum id.',
      clientImage:
        'https://i.pinimg.com/originals/75/8b/70/758b70c854cfc2bd1c3a0fbc903fb7bb.png',
    },
    {
      id: 'quote-2',
      clientName: 'Mary Shelley',
      clientText:
        'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque quis tellus est. Sed sapien mi. Mauris diam quam, consequat vitae neque in, pretium efficitur mauris. Donec vulputate consectetur ipsum non dictum. Aenean enim dui.',
      clientImage:
        'https://i.pinimg.com/originals/75/8b/70/758b70c854cfc2bd1c3a0fbc903fb7bb.png',
    },
    {
      id: 'quote-3',
      clientName: 'Jane Doe',
      clientText:
        'Etiam accumsan dui a lacus pulvinar gravida. Duis eu congue urna. Pellentesque facilisis justo vitae enim viverra dictum. Proin non lacus. Phasellus in blandit leo, a maximus magna. Phasellus cursus eros sit amet lacus fermentum ultrices. Etiam eget sapien at erat.',
      clientImage:
        'https://i.pinimg.com/originals/75/8b/70/758b70c854cfc2bd1c3a0fbc903fb7bb.png',
    },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 4,
      isStarred: true,
      oldPrice: 35,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/945688/pexels-photo-945688.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/276566/pexels-photo-276566.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6758245/pexels-photo-6758245.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      oldPrice: 50,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/7018400/pexels-photo-7018400.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/2440471/pexels-photo-2440471.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/5998138/pexels-photo-5998138.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6538933/pexels-photo-6538933.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      oldPrice: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6782476/pexels-photo-6782476.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/7088273/pexels-photo-7088273.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      oldPrice: 20,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/6969824/pexels-photo-6969824.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      oldPrice: 18,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/6588592/pexels-photo-6588592.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/6947272/pexels-photo-6947272.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/4352247/pexels-photo-4352247.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6969834/pexels-photo-6969834.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6480198/pexels-photo-6480198.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/1374125/pexels-photo-1374125.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/833045/pexels-photo-833045.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      oldPrice: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: true,
      image:
        'https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/1648768/pexels-photo-1648768.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/276534/pexels-photo-276534.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      compare: false,
    },
    {
      id: 'blue-chair-01',
      name: 'Aenean Ru Chair 01',
      category: 'chair',
      price: 29,
      oldPrice: 35,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/2258083/pexels-photo-2258083.jpeg?cs=srgb&dl=pexels-artem-lysenko-2258083.jpg&fm=jpg',
    },
    {
      id: 'blue-chair-02',
      name: 'Aenean Ru Chair 02',
      category: 'chair',
      price: 20,
      oldPrice: 29,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/3259922/pexels-photo-3259922.jpeg?cs=srgb&dl=pexels-bruno-cervera-3259922.jpg&fm=jpg',
    },
    {
      id: 'blue-chair-03',
      name: 'Aenean Ru Chair 03',
      category: 'chair',
      price: 24,
      oldPrice: null,
      stars: 2,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/8286101/pexels-photo-8286101.jpeg?cs=srgb&dl=pexels-ron-lach-8286101.jpg&fm=jpg',
    },
    {
      id: 'blue-chair-04',
      name: 'Aenean Ru Chair 04',
      category: 'chair',
      price: 40,
      oldPrice: null,
      stars: 4,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/8987430/pexels-photo-8987430.jpeg?cs=srgb&dl=pexels-ksenia-chernaya-8987430.jpg&fm=jpg',
    },
    {
      id: 'blue-chair-05',
      name: 'Aenean Ru Chair 05',
      category: 'chair',
      price: 32,
      oldPrice: 40,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/8082560/pexels-photo-8082560.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-8082560.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-01',
      name: 'Aenean Ru Sofa 01',
      category: 'sofa',
      price: 120,
      oldPrice: 150,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6758245/pexels-photo-6758245.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6758245.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-02',
      name: 'Aenean Ru Sofa 02',
      category: 'sofa',
      price: 120,
      oldPrice: 150,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6934175/pexels-photo-6934175.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6934175.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-03',
      name: 'Aenean Ru Sofa 03',
      category: 'sofa',
      price: 100,
      oldPrice: 120,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?cs=srgb&dl=pexels-martin-p%C3%A9chy-1866149.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-04',
      name: 'Aenean Ru Sofa 04',
      category: 'sofa',
      price: 150,
      oldPrice: 179,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6947272/pexels-photo-6947272.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6947272.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-05',
      name: 'Aenean Ru Sofa 05',
      category: 'sofa',
      price: 150,
      oldPrice: null,
      stars: 5,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6588592/pexels-photo-6588592.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6588592.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-06',
      name: 'Aenean Ru Sofa 06',
      category: 'sofa',
      price: 165,
      oldPrice: 177,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6969777/pexels-photo-6969777.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6969777.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-07',
      name: 'Aenean Ru Sofa 07',
      category: 'sofa',
      price: 220,
      oldPrice: 249,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6969834/pexels-photo-6969834.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6969834.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-08',
      name: 'Aenean Ru Sofa 08',
      category: 'sofa',
      price: 199,
      oldPrice: null,
      stars: 2,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/8433453/pexels-photo-8433453.jpeg?cs=srgb&dl=pexels-mart-production-8433453.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-09',
      name: 'Aenean Ru Sofa 09',
      category: 'sofa',
      price: 180,
      oldPrice: null,
      stars: 4,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6980718/pexels-photo-6980718.jpeg?cs=srgb&dl=pexels-max-vakhtbovych-6980718.jpg&fm=jpg',
    },
    {
      id: 'grey-sofa-10',
      name: 'Aenean Ru Sofa 10',
      category: 'sofa',
      price: 160,
      oldPrice: 189,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/8581040/pexels-photo-8581040.jpeg?cs=srgb&dl=pexels-rodnae-productions-8581040.jpg&fm=jpg',
    },
    {
      id: 'wood-table-01',
      name: 'Aenean Re Table 01',
      category: 'table',
      price: 89,
      oldPrice: 99,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/2451264/pexels-photo-2451264.jpeg?cs=srgb&dl=pexels-scott-webb-2451264.jpg&fm=jpg',
    },
    {
      id: 'wood-table-02',
      name: 'Aenean Re Table 02',
      category: 'table',
      price: 119,
      oldPrice: null,
      stars: 4,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/631411/pexels-photo-631411.jpeg?cs=srgb&dl=pexels-ingo-joseph-631411.jpg&fm=jpg',
    },
    {
      id: 'wood-table-03',
      name: 'Aenean Re Table 03',
      category: 'table',
      price: 100,
      oldPrice: 119,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/269220/pexels-photo-269220.jpeg?cs=srgb&dl=pexels-pixabay-269220.jpg&fm=jpg',
    },
    {
      id: 'dining-01',
      name: 'Aenean Ru Tob dining 01',
      category: 'dining',
      price: 160,
      oldPrice: 180,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/265940/pexels-photo-265940.jpeg?cs=srgb&dl=pexels-pixabay-265940.jpg&fm=jpg',
    },
    {
      id: 'dining-02',
      name: 'Aenean Ru Tob dining 02',
      category: 'dining',
      price: 159,
      oldPrice: 185,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/1243337/pexels-photo-1243337.jpeg?cs=srgb&dl=pexels-expect-best-1243337.jpg&fm=jpg',
    },
    {
      id: 'dining-03',
      name: 'Aenean Ru Tob dining 03',
      category: 'dining',
      price: 199,
      oldPrice: 230,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/5775055/pexels-photo-5775055.jpeg?cs=srgb&dl=pexels-nicole-michalou-5775055.jpg&fm=jpg',
    },
    {
      id: 'dining-04',
      name: 'Aenean Ru Tob dining 04',
      category: 'dining',
      price: 120,
      oldPrice: null,
      stars: 3,
      promo: null,
      newFurniture: true,
      favoritue: false,
      image:
        'https://images.pexels.com/photos/6021895/pexels-photo-6021895.jpeg?cs=srgb&dl=pexels-ksenia-chernaya-6021895.jpg&fm=jpg',
    },
  ],
  cart: {
    products: [],
  },
};

export default initialState;
